<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Almoxarifado EMI</title>

    <!-- Bootstrap core CSS -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../assets/css/signin.css" rel="stylesheet">
</head>

<body>
<?php if(isset($_SESSION['erro']) && $_SESSION['erro'] != null && $_SESSION['erro'] != ''){ ?>
    <div class="alert alert-danger" role="alert">Login Inválido</div>
    <?php $_SESSION['erro'] = null;
} ?>
<div class="container">

    <form class="form-signin" action="/login" method="POST">
        <h2 class="form-signin-heading">Login</h2>
        <label for="inputMatricula" class="sr-only">Matrícula</label>
        <input type="text" id="inputMatricula" class="form-control" name="matricula" placeholder="Matricula" required autofocus>
        <label for="inputPassword" class="sr-only">Senha</label>
        <input type="password" id="inputPassword" class="form-control" name="senha" placeholder="Password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

</div> <!-- /container -->
</body>
</html>