<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

    <title>Itens EMI</title>

    <!-- Bootstrap core CSS -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../assets/css/sticky-footer-navbar.css" rel="stylesheet">
    <link href="../assets/css/starter-template.css" rel="stylesheet">
    <link href="../assets/css/blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../assets/js/ie-emulation-modes-warning.js"></script>
</head>

<body>
<?php if(isset($_SESSION['erro']) && $_SESSION['erro'] != null && $_SESSION['erro'] != ''){ ?>
    <div class="alert alert-danger" role="alert">Falha ao salvar dados!</div>
    <?php $_SESSION['erro'] = null;
} ?>
<?php if(isset($_SESSION['sucesso']) && $_SESSION['sucesso'] != null && $_SESSION['sucesso'] != ''){ ?>
    <div class="alert alert-danger" role="alert">Dados salvos com sucesso!</div>
    <?php $_SESSION['sucesso'] = null;
} ?>
<div class="blog-masthead" style="margin-top: -3%; font-size: 1.5em;">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="/itens">Incial</a>
            <a class="blog-nav-item" href="/itens/save">Add Item</a>
            <a class="blog-nav-item" href="/servidor">Servidor</a>
            <a class="blog-nav-item" href="/servidor/save">Add Servidor</a>
            <a class="blog-nav-item" href="/retirada">Retirada</a>
            <a class="blog-nav-item" href="/sobre">Sobre</a>
            <a class="blog-nav-item" href="/sair">Sair</a>
        </nav>
    </div>
</div>

<!-- Begin page content -->
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>
                    Nome
                </td>
                <td>
                    Quantidade
                </td>
                <td>
                    Código de Barra
                </td>
                <td>
                    Corredor
                </td>
                <td>
                    Prateleira
                </td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->result as $itens) { ?>
                <tr>
                    <td>
                        <?= $itens['nome'] ?>
                    </td>
                    <td>
                        <?= $itens['quantidade'] ?>
                    </td>
                    <td>
                        <?= $itens['cod_barra'] ?>
                    </td>
                    <td>
                        <?= $itens['desc_corredor'] ?>
                    </td>
                    <td>
                        <?= $itens['desc_prateleira'] ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<footer class="footer">
    <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
    </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>
